import type { Metadata } from "next";
import "../globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { Inter as FontSans } from "next/font/google";
import { cn } from "../../lib/utils";
import { ModeToggle } from "@/components/mode-toggle";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Define the metadata separately outside the component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed bottom-4 right-4 z-50">
            <ModeToggle></ModeToggle>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
