import type { Metadata } from "next";
import "../globals.css";

import { useRouter } from "next/router";
import { ChevronLeftIcon } from "@radix-ui/react-icons";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter as FontSans } from "next/font/google";
import { cn } from "../../lib/utils";
import { ModeToggle } from "@/components/mode-toggle";
import { Button, buttonVariants } from "@/components/ui/button";
import { Toaster } from "@/components/ui/toaster";

import Link from "next/link";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Define the metadata separately outside the component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed top-6 left-6 z-50">
            <Link
              className={buttonVariants({ variant: "ghost" })}
              href={"/home"}
            >
              <ChevronLeftIcon className="h-4 w-4" />
            </Link>
          </div>
          <div className="fixed bottom-4 right-4 z-50">
            <ModeToggle></ModeToggle>
          </div>
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
